test(ci): check MD5 of snap installer

diff --git a/windows.gitlab-ci.yml b/windows.gitlab-ci.yml
--- a/windows.gitlab-ci.yml
+++ b/windows.gitlab-ci.yml
@@ -1,4 +1,4 @@
-test_windows:
+install_snap:
   tags:
     - windows
   stage: test
@@ -11,7 +11,8 @@ test_windows:
     TEMP_DIR: 'D:\\tmp'
     TAG: master
     PROPERTIES_PATH: win.conf
-    SNAP_INSTALLER: "snap_all_windows-%VERSION%.exe"
+    SNAP_INSTALLER_EXE: "snap_all_windows-%VERSION%.exe"
+    NEXUS_URL: "https://nexus.snap-ci.ovh/repository/snap-maven-releases/org/esa/snap/installers-snapshot/snap_all_windows/%VERSION%/"
     TEST_DATA_LIST: singleTestData.txt
     JAVA_HOME: C:\\Program Files\\Zulu\\zulu-11
     JAVA_OPTIONS: >-
@@ -23,21 +24,51 @@ test_windows:
     TRANSFER_METER_FREQUENCY: "2s"
     # Use fast compression for artifacts, resulting in larger archives
     ARTIFACT_COMPRESSION_LEVEL: "slowest"
-  cache: []
   before_script:
-    - echo %USERNAME%
-    # build project
+    - echo username = %USERNAME%
+    # build maven project
     - call mvn %MAVEN_CLI_OPTS% package install
+    # print local variables
+    - echo CI_PROJECT_DIR       = %CI_PROJECT_DIR%
+    - echo DEST_DIR             = %DEST_DIR%
+    - echo DL_DIR               = %DL_DIR%
+    - echo NEXUS_URL            = %NEXUS_URL%
+    - echo REPORT_DIR           = %REPORT_DIR%
+    - echo SCOPE                = %SCOPE%
+    - echo SNAP_DIR             = %SNAP_DIR%
+    - echo SNAP_INSTALLER_EXE   = %SNAP_INSTALLER_EXE%
+    - echo VERSION              = %VERSION%
+    - echo S3_REPORTS           = %S3_REPORTS%
     # Clean old report
     - rd /s /q %REPORT_DIR%
     - mkdir %REPORT_DIR% && mkdir %REPORT_DIR%\report && mkdir %REPORT_DIR%\report\output
     - python -m venv snapenv && call .\snapenv\Scripts\activate.bat && pip3 install -r %CI_PROJECT_DIR%\requirements.txt
     # Produce a list of tests to run
     - python %CI_PROJECT_DIR%\pygpt\filter_json.py gpt-tests-resources\tests %SCOPE% %REPORT_DIR%
-    # Install snap
-    - curl --progress-bar "https://nexus.snap-ci.ovh/repository/snap-maven-releases/org/esa/snap/installers-snapshot/snap_all_windows/%VERSION%/snap_all_windows-%VERSION%.exe" >> "%DL_DIR%\%SNAP_INSTALLER%"
-    - echo "Install SNAP" && "%DL_DIR%\%SNAP_INSTALLER%" -q -dir "%SNAP_DIR%" -console -overwrite -v
+    # Download SNAP application from Nexus 
+    - curl --progress-bar "%NEXUS_URL%/%SNAP_INSTALLER_EXE%" >> "%DL_DIR%\%SNAP_INSTALLER_EXE%"
+    # Retrieve (from Nexus) MD5 checksum of SNAP installer executable file and set into variable
+    - FOR /F "tokens=* USEBACKQ" %g IN (`curl ""%NEXUS_URL%/%SNAP_INSTALLER_EXE%".md5"`) do (SET "SNAP_INSTALLER_MD5=%g")
+    - echo SNAP_INSTALLER_MD5 = %SNAP_INSTALLER_MD5%
+    # Compute MD5 checksum of downloaded SNAP installer executable
+    - FOR /F "tokens=* USEBACKQ" %x IN (`certutil -hashfile "%DL_DIR%\%SNAP_INSTALLER_EXE%" MD5`) do (SET "LOCAL_MD5=%x") 
+    - echo LOCAL_MD5 = %LOCAL_MD5%
+    # 
+    # Compare the MD5 values. If different, fail the job/pipeline
+    #
+    - |
+      if /i not %SNAP_INSTALLER_MD5%==%LOCAL_MD5% (
+        echo "MD5 checksum error - downloaded file 'SNAP installer' (%SNAP_INSTALLER_EXE%) is corrupt."
+        echo "ERROR - exit from job / pipeline !"
+        exit 42
+      ) 
+    # Install SNAP aplication on destination Windows VM
+    - echo "Install SNAP (version %VERSION%)" && "%DL_DIR%\%SNAP_INSTALLER_EXE%" -q -dir "%SNAP_DIR%" -console -overwrite -v
     - echo "Post install" && xcopy "%DL_DIR%\snap.properties" "%SNAP_DIR%\etc" /Y
+
+test_windows:
+  extends: install_snap 
+  cache: []
   script:
     - run_tests.bat
   after_script:
